### ISSUE TITLE
Game crash when trying to load MogMogCheck

### ISSUE THREAD

**Issue by Moonlight-Everlit** [Haselnussbomber/MogMogCheck#13]
Log:

`2024-07-04 08:46:48.424 +02:00 [INF] [PLUGINM] Plugin was outdated, adding anyways: MogMogCheck.dll
Dalamud.Plugin.Internal.Exceptions.PluginPreconditionFailedException: Unable to load MogMogCheck, incompatible API level 9
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 326
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 1667`

**Comment by Haselnussbomber** [comment]
The plugin isn't loading because it's not updated yet.
If you're experiencing crashes, then something else is doing that.

**Comment by Moonlight-Everlit** [comment]
That's the weird thing - I removed MogMogCheck and LeveHelper and I had no more crashes.
I started it 3 times with the plugins in and 3 times without and it crashed every time they were in my InstalledPlugins folder.

**Comment by Haselnussbomber** [comment]
I just tried it myself with the latest release, and it's simply not loading, as expected:
```
2024-07-04 14:28:36.668 +02:00 [INF] [PLUGINM] ============= LoadPluginsAsync(FrameworkTickAsync) START =============
2024-07-04 14:28:36.668 +02:00 [INF] [PLUGINM] Loading dev plugin LeveHelper
2024-07-04 14:28:36.668 +02:00 [INF] [PLUGINM] Loading dev plugin Yo-kai Check
2024-07-04 14:28:36.668 +02:00 [INF] [PLUGINM] Loading plugin MogMogCheck
2024-07-04 14:28:36.668 +02:00 [INF] [PLUGINM] Loading dev plugin HaselTweaks
2024-07-04 14:28:36.669 +02:00 [INF] [PLUGINM] MogMogCheck defaultState: true wantedByAnyProfile: true loadPlugin: true
2024-07-04 14:28:36.669 +02:00 [WRN] [LOCALPLUGIN] Unable to load MogMogCheck, incompatible API level 9
2024-07-04 14:28:36.669 +02:00 [INF] [PLUGINM] Plugin was outdated, adding anyways: MogMogCheck.dll
Dalamud.Plugin.Internal.Exceptions.PluginPreconditionFailedException: Unable to load MogMogCheck, incompatible API level 9
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 326
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 1667
```
The same message is shown for dozens of other plugins, but no crash.
I really don't know why it would be crashing for you. I guess you'll have to remove it for now then.
Sorry this is happening, but no idea. 🤷‍♂️
